name: edrol_ai
description: Advanced Premium AI Assistant
publish_to: 'none'
version: 1.0.1+2 # Ye version Play Store me update ke liye zaroori hai

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3                  # Downloading models ke liye
  path_provider: ^2.1.1        # Phone me save karne ke liye
  http: ^1.2.0                 # API calls ke liye
  shared_preferences: ^2.2.2   # 👈 Offline Timer ke liye
  url_launcher: ^6.2.1         # 👈 Cosmofeed Payment Link kholne ke liye
  firebase_core: ^2.32.0       # 👈 Edrolai Firebase Connect karne ke liye
  firebase_database: ^10.5.0   # 👈 Live Brain aur Rules Update ke liye
  image_picker: ^1.1.2         # Image pick karne ke liye
  translator: ^0.3.3           # 👈 Hinglish se English Translate karne ke liye (Image Gen)
    llama_cpp_dart: any
      # 👈 Offline Chat Brain (Qwen GGUF) chalane ke liye

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # App ka professional logo set karne ke liye

# Ye magic code teri app ka logo automatically badal dega
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/logo1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo1.png
    - assets/images/logo2.png
    - assets/images/aditi.jpg 
